// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA84xOzCJbhFw0O1zcQUuh8cPp03sFeqSY',
    appId: '1:833290142594:web:c69810ae3104aa80a5059b',
    messagingSenderId: '833290142594',
    projectId: 'krakenanime-6f27a',
    authDomain: 'krakenanime-6f27a.firebaseapp.com',
    storageBucket: 'krakenanime-6f27a.appspot.com',
    measurementId: 'G-K994T17GXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA6lK0ziwzVKxOdV7X6U3kHddPhUbv-og',
    appId: '1:833290142594:android:383b43e2520d34dba5059b',
    messagingSenderId: '833290142594',
    projectId: 'krakenanime-6f27a',
    storageBucket: 'krakenanime-6f27a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCucwyYkYx92D0_2sjI-_EDYShUhIAGbro',
    appId: '1:833290142594:ios:680bd9de07c3f824a5059b',
    messagingSenderId: '833290142594',
    projectId: 'krakenanime-6f27a',
    storageBucket: 'krakenanime-6f27a.appspot.com',
    iosBundleId: 'com.example.krakenAnime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCucwyYkYx92D0_2sjI-_EDYShUhIAGbro',
    appId: '1:833290142594:ios:680bd9de07c3f824a5059b',
    messagingSenderId: '833290142594',
    projectId: 'krakenanime-6f27a',
    storageBucket: 'krakenanime-6f27a.appspot.com',
    iosBundleId: 'com.example.krakenAnime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA84xOzCJbhFw0O1zcQUuh8cPp03sFeqSY',
    appId: '1:833290142594:web:bce0603212ad01afa5059b',
    messagingSenderId: '833290142594',
    projectId: 'krakenanime-6f27a',
    authDomain: 'krakenanime-6f27a.firebaseapp.com',
    storageBucket: 'krakenanime-6f27a.appspot.com',
    measurementId: 'G-D0DK1ENDM3',
  );
}
